version: "3.2"
services:
  php:
    build: './php/'
    volumes:
      - ./blog/:/var/www/html/
  apache:
    build: './apache/'
    depends_on:
      - php
      - mysql
    ports:
      - "8080:80"
    volumes:
      - ./blog/:/var/www/html/
  mysql:
    build: './mysql/'
    environment:
      - MYSQL_ROOT_PASSWORD: "toor"
      - MYSQL_DATABASE: "blog"
      - MYSQL_USER: "rootUser"
      - MYSQL_PASSWORD: "toor"